Repository hassio-addons/addon-tasmoadmin, pull requests merged in 2022-06, with the labels that each got.

#240 ⬆️ Upgrades add-on base image to 12.0.0
  tasmoadmin/Dockerfile
  tasmoadmin/build.yaml
  tasmoadmin/rootfs/etc/cont-init.d/nginx.sh
  tasmoadmin/rootfs/etc/cont-init.d/tasmoadmin.sh
  tasmoadmin/rootfs/etc/fix-attrs.d/01-tasmoadmin
  tasmoadmin/rootfs/etc/php8/blacklist.txt
  tasmoadmin/rootfs/etc/php8/conf.d/99-tasmoadmin.ini
  tasmoadmin/rootfs/etc/php8/php-fpm.d/www.conf
  tasmoadmin/rootfs/etc/services.d/nginx/finish
  tasmoadmin/rootfs/etc/services.d/nginx/run
  tasmoadmin/rootfs/etc/services.d/php-fpm/finish
  tasmoadmin/rootfs/etc/services.d/php-fpm/run
Labels: minor, dependencies

#241 :books: Use new My Home Assistant link format
  tasmoadmin/DOCS.md
Labels: documentation

#243 ⬆️ Upgrades TasmoAdmin to v2.0.0-beta6
  tasmoadmin/Dockerfile
Labels: minor, dependencies

#245 ⬆️ Upgrades TasmoAdmin to v2.0.0-beta8
  tasmoadmin/Dockerfile
Labels: dependencies

#246 Fix PHP opcache blacklist file
  tasmoadmin/rootfs/etc/php8/conf.d/99-tasmoadmin.ini
Labels: bugfix

#247 ⬆️ Upgrades TasmoAdmin to v2.0.0-beta9
  tasmoadmin/Dockerfile
Labels: dependencies

#248 :ambulance: Fix missing multibyte string handling/conversion modules
  tasmoadmin/Dockerfile
Labels: bugfix

#249 ⬆️ Upgrades nginx to 1.22.0-r1
  tasmoadmin/Dockerfile
Labels: dependencies

#250 ⬆️ Upgrades TasmoAdmin to v2.0.0
  tasmoadmin/Dockerfile
Labels: minor, dependencies
