Repository hassio-addons/addon-tasmoadmin, pull requests merged in 2022-12, with the labels that each got.

#268 ⬆️ Upgrades add-on base image to 13.0.0
  tasmoadmin/Dockerfile
  tasmoadmin/build.yaml
  tasmoadmin/rootfs/etc/php81/blacklist.txt
  tasmoadmin/rootfs/etc/php81/conf.d/99-tasmoadmin.ini
  tasmoadmin/rootfs/etc/php81/php-fpm.d/www.conf
  tasmoadmin/rootfs/etc/services.d/php-fpm/run
Labels: minor, dependencies

#269 :hammer: Migrate old-style S6 scripts to s6-rc.d
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/dependencies.d/base
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/run
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/type
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/up
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/init-tasmoadmin/dependencies.d/base
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/init-tasmoadmin/run
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/init-tasmoadmin/type
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/init-tasmoadmin/up
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/init-nginx
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/php-fpm
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/nginx/finish
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/nginx/type
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/php-fpm/dependencies.d/init-tasmoadmin
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/php-fpm/finish
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/php-fpm/run
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/php-fpm/type
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/init-nginx
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/init-tasmoadmin
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/nginx
  tasmoadmin/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/php-fpm
  tasmoadmin/rootfs/etc/services.d/nginx/run
  tasmoadmin/rootfs/etc/services.d/php-fpm/finish
Labels: maintenance

#270 :stethoscope: Add healthcheck to improve HA watchdog
  tasmoadmin/Dockerfile
Labels: new-feature

#271 ⬆️ Upgrades TasmoAdmin to v2.2.0
  tasmoadmin/Dockerfile
Labels: minor, dependencies

#274 🔨 Fix healthcheck for SSL enabled instances
  tasmoadmin/Dockerfile
Labels: bugfix
