Repository hassio-addons/addon-tasmoadmin, pull requests merged in 2023-03, with the labels that each got.

#287 ⬆️ Upgrades add-on base image to 13.1.3
  tasmoadmin/Dockerfile
  tasmoadmin/build.yaml
Labels: dependencies

#288 ⬆️ Upgrades TasmoAdmin to v3.0.1
  tasmoadmin/Dockerfile
Labels: minor, dependencies

#289 🔨 Change nginx configuration for v3 upgrade
  tasmoadmin/rootfs/etc/nginx/nginx-ssl.conf
  tasmoadmin/rootfs/etc/nginx/nginx.conf
Labels: refactor

#290 🐛 Fix nginx routing for /
  tasmoadmin/rootfs/etc/nginx/nginx-ssl.conf
  tasmoadmin/rootfs/etc/nginx/nginx.conf
Labels: bugfix

#292 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  tasmoadmin/Dockerfile
Labels: maintenance
