Repository hassio-addons/addon-tasmoadmin, pull requests merged in 2023-01, with the labels that each got.

#277 ⬆️ Upgrades php to 8.1.14
  tasmoadmin/Dockerfile
Labels: dependencies

#276 ⬆️ Upgrades TasmoAdmin to v2.3.3
  tasmoadmin/Dockerfile
Labels: minor, dependencies

#278 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  tasmoadmin/.README.j2
  tasmoadmin/DOCS.md
Labels: maintenance

#279 ⬆️ Upgrades add-on base image to 13.1.0
  tasmoadmin/Dockerfile
  tasmoadmin/build.yaml
Labels: dependencies

#280 ⬆️ Upgrades git to 2.38.3-r1
  tasmoadmin/Dockerfile
Labels: dependencies
